### ISSUE TITLE
防止用dired连续打开多个子文件夹导致其全部被加入history里面，污染列表

### ISSUE THREAD

**Issue by QiangF** [jixiuf/ivy-dired-history#2]
看看这样弄怎么样

    (defvar ivy-dired-history-update-timer nil)

    (defun ivy-dired-history-update()
        "Update variable `ivy-dired-history-variable'."
        (when ivy-dired-history-update-timer
        (cancel-timer ivy-dired-history-update-timer))
        (setq ivy-dired-history-update-timer
            (let ((dir (dired-current-directory)))
                (run-with-timer 15 nil `(lambda ()
                                        (ivy-dired-history--update ,dir))))))

**Comment by jixiuf** [comment]
我很久不用这个包了 你觉得合适提个pr 我来merge

**Comment by QiangF** [comment]
Done. https://github.com/jixiuf/ivy-dired-history/pull/3
